remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme  # Required for remote_theme to work

title: "Nilabja Bhattacharjee"
description: "PhD Student | Computational Biology | IIIT Delhi"

logo: /WhatsApp Image 2025-10-23 at 19.19.22_c9b61628.jpg
show_downloads: false
